version: "3.9"

services:
  php:
    container_name: php
    build:
      context: .
      dockerfile: php/Dockerfile
    extra_hosts:
      - host.docker.internal:host-gateway

  node:
    container_name: node
    build:
      context: .
      dockerfile: node/Dockerfile
    extra_hosts:
      - host.docker.internal:host-gateway