name: docker-hub-push-images

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            php:
              - 'php/**'

      - name: Set up QEMU
        if: steps.changes.outputs.php == 'true'
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        if: steps.changes.outputs.php == 'true'
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        if: steps.changes.outputs.php == 'true'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push
        if: steps.changes.outputs.php == 'true'
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./php/Dockerfile
          tags: rguasch/php:latest
